# Generated by Django 3.0.4 on 2020-04-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
