# Generated by Django 3.0.4 on 2020-04-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('image', models.TextField()),
                ('summary', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
